### ISSUE TITLE
PHP version req?

### ISSUE THREAD

**Issue by sbramley** [lubusIN/laravel-decomposer#6]
I'm getting the following:
`[InvalidArgumentException]
  Could not find package lubusin/laravel-decomposer at any version matching y
  our PHP version 5.5.9.0
`
Is this only supported on certain versions of php?

**Comment by introwit** [comment]
@sbramley It's minimum requirement is PHP 5.6 , as the support for PHP 5.* is officially ended we would advise you to atleast move to 5.6 atleast if possible. If you still can't upgrade to PHP 5.6 due to some reasons let us know, we would might lower the dependency for you to use the package, as we aren't using any PHP 7 specific feature yet.

**Comment by sbramley** [comment]
I'm checking into it now, we're running on Elastic Beanstalk on AWS and I know it's a little behind in terms of versioning

**Comment by introwit** [comment]
@sbramley let us know the final call you make.
